sudo: false

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master


before_script:
  - chmod +x gradlew


script:
  - ./gradlew clean check
  - ./gradle test
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.gradle
