sudo: false

install: gradle wrapper --gradle-version 4.4.1

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master


before_script:
  - chmod +x gradlew


script:
  - ./gradlew clean test

cache:
  directories:
  - $HOME/.gradle
